# Generated by Django 6.0.2 on 2026-07-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_cv_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_application_per_email_and_edition',
        ),
    ]
