# Generated by Django 6.0.2 on 2026-08-09 20:07

import applications.models
import core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_application_unique_application_per_email_and_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=core.storage.PrivateMediaStorage(), upload_to=core.storage.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), applications.models.validate_file_size]),
        ),
    ]
