# Generated by Django 6.0.2 on 2026-08-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='points_baseline',
            field=models.PositiveIntegerField(blank=True, help_text="Pontos com que o participante comecou a edicao. Fica vazio ate a edicao passar a 'A decorrer'. A pontuacao atual e calculada a partir daqui e das notas das tasks.", null=True, verbose_name='Pontos iniciais'),
        ),
    ]
