# Generated by Django 6.0.2 on 2026-08-09 21:20

from django.db import migrations


def assign_points_to_active_editions(apps, schema_editor):
    """
    O sistema de pontos so passa a atribuir pontos_baseline quando
    uma edicao TRANSITA para "active". Edicoes que ja estavam
    "active" antes desta funcionalidade existir nunca disparam essa
    transicao, por isso esta migration faz esse backfill uma vez,
    para quem ja esta a participar numa edicao a decorrer.
    """

    Edition = apps.get_model("editions", "Edition")
    Participation = apps.get_model("applications", "Participation")

    for edition in Edition.objects.filter(status="active"):
        Participation.objects.filter(
            edition=edition,
            status="active",
            points_baseline__isnull=True,
        ).update(
            points_baseline=edition.initial_points
        )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_participation_points_baseline'),
        ('editions', '0003_edition_initial_points'),
    ]

    operations = [
        migrations.RunPython(
            assign_points_to_active_editions,
            migrations.RunPython.noop,
        ),
    ]
