# Generated by Django 6.0.2 on 2026-08-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_backfill_points_baseline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participação', 'verbose_name_plural': 'Participações'},
        ),
    ]
