# Generated by Django 6.0.2 on 2026-07-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_remove_profile_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_participant',
        ),
    ]
