# Generated by Django 6.0.5 on 2026-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('theme', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('upcoming', 'A anunciar'), ('open', 'Candidaturas abertas'), ('closed', 'Candidaturas fechadas'), ('active', 'A decorrer'), ('finished', 'Concluída')], default='upcoming', max_length=20)),
                ('applications_open', models.DateField(blank=True, null=True)),
                ('applications_close', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edição',
                'verbose_name_plural': 'Edições',
                'ordering': ['-year'],
            },
        ),
    ]
