# Generated by Django 6.0.2 on 2026-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='status',
            field=models.CharField(choices=[('upcoming', 'A anunciar'), ('open', 'Candidaturas abertas'), ('closed', 'Candidaturas fechadas'), ('full', 'Vagas preenchidas totalmente'), ('active', 'A decorrer'), ('finished', 'Concluída')], default='upcoming', max_length=20),
        ),
    ]
