# Generated by Django 6.0.2 on 2026-08-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_alter_edition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='initial_points',
            field=models.PositiveIntegerField(default=100, help_text="Pontos atribuidos a cada participante quando esta edicao passa a 'A decorrer'. Quem chegar a 0 pontos fica marcado para saida do programa (a decisao final e sempre manual).", verbose_name='Pontos iniciais'),
        ),
    ]
