# Generated by Django 6.0.2 on 2026-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='admin_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submetida'), ('revision', 'Necessita revisão'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='submitted', max_length=20),
        ),
    ]
