# Generated by Django 6.0.2 on 2026-07-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasksubmission_admin_feedback_tasksubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task atribuída'), ('task_feedback', 'Feedback da task')], default='task_assigned', max_length=30),
            preserve_default=False,
        ),
    ]
