# Generated by Django 6.0.2 on 2026-07-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task atribuída'), ('task_feedback', 'Feedback da task'), ('general', 'Geral')], default='general', max_length=20),
        ),
    ]
