# Generated by Django 6.0.2 on 2026-07-31 12:50

import django.core.validators
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='file',
            field=models.FileField(upload_to='task_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip,pdf']), tasks.models.validate_file_size]),
        ),
    ]
