# Generated by Django 6.0.2 on 2026-08-09 20:07

import core.storage
import django.core.validators
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasksubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='file',
            field=models.FileField(storage=core.storage.PrivateMediaStorage(), upload_to=core.storage.task_submission_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'pdf']), tasks.models.validate_file_size]),
        ),
    ]
