# Generated by Django 6.0.2 on 2026-08-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_participation_points_baseline'),
        ('tasks', '0006_alter_tasksubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_value',
            field=models.PositiveIntegerField(default=10, help_text='Quanto vale esta task. Um participante que receba a nota maxima nao perde pontos; nota 0 faz perder estes pontos todos.', verbose_name='Pontos da task'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='grade',
            field=models.PositiveIntegerField(blank=True, help_text='Nota de 0 ate ao valor da task. Deixar vazio enquanto nao for avaliada.', null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='applications.participation'),
        ),
    ]
