# Generated by Django 6.0.2 on 2026-09-26 19:34

import core.storage
import django.core.validators
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_notification_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='is_missing',
            field=models.BooleanField(default=False, help_text='Gerada automaticamente porque o prazo expirou sem entrega.', verbose_name='Não entregue (automática)'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.PrivateMediaStorage(), upload_to=core.storage.task_submission_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'pdf']), tasks.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
